apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-beacon 
spec:
  selector:
    matchLabels:
      app: warehouse-beacon 
  replicas: 1
  template:
    metadata:
      labels:
        app: warehouse-beacon
    spec:
      containers:
        - name: warehouse-beacon 
          image: quay.research.chop.edu/evansj/warehouse-beacon
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: warehosue-beacon-svc
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: warehouse-beacon 
spec:
  type: LoadBalancer
  selector:
    app: warehouse-beacon 
  ports:
  - port: 8080
    name: insecure
    targetPort: 8080
    protocol: TCP
